version: '3.8'

services:
  bot:
    build: .
    container_name: shoxzamon_milk_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/shoxzamon.db
